spring.application.name=demo

# ===============================
# DATABASE (PostgreSQL - Docker)
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/topologydb
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.docker.compose.file=C:/Users/Utilizador/Desktop/PF/demo/demo/docker-compose.yml


# ===============================
# SQL INIT (executa scripts)
# ===============================

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/topologies.sql
spring.sql.init.continue-on-error=true

# ===============================
# JPA (mesmo não usando Hibernate)
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
